### ISSUE TITLE
VM Staff

### ISSUE THREAD

**Issue by white-haired-uncle** [matsjoyce/LotIWikiGen#16]
https://wiki.wesnoth.org/LotI_Items#Violent_Mage.27s_Staff_.E2.80.93_staff

`New bonus attack: violent beatdown (100%, 100% melee, copy of staff)`

No idea what the parenthetical items are.

**Comment by matsjoyce** [comment]
Should be more Englishy now: `New bonus attack: violent beatdown (100% damage and 100% attacks of staff, melee)`
