### ISSUE TITLE
Dying Dreams – craftable as any armour

### ISSUE THREAD

**Issue by white-haired-uncle** [matsjoyce/LotIWikiGen#17]
It's a helm, not craftable.

There have been some recent changes to item_list.cfg, FWIW.  Probably more in the near future (https://github.com/Dugy/Legend_of_the_Invincibles/issues/755?notification_referrer_id=NT_kwDOCA7sp7UxMDIwNDcyNTQyOToxMzUxOTU4MTU#issuecomment-2097147250)

**Comment by matsjoyce** [comment]
Fixed in b80ebb0, along with a lot of other updates (and script fixes :sweat: although I am always suprised when they do work given how hacky they are)
