### ISSUE TITLE
Incorrect description for technocrat advancement

### ISSUE THREAD

**Issue by arodiss** [matsjoyce/LotIWikiGen#8]
check this: https://wiki.wesnoth.org/LotI_Unit_Advancements#Shooting_Bullets_that_Penetrate_Armour_Better_.E2.80.93_bullets

**Comment by arodiss** [comment]
PS
found some more: https://wiki.wesnoth.org/LotI_Unit_Advancements#Attacking_Horrendously_with_Berserk_Attacks_.E2.80.93_berserk2_damage
https://wiki.wesnoth.org/LotI_Unit_Advancements#Decreasing_Enemies.27_Arcane_Resistance_by_8.25_and_Fire_and_Cold_Resistances_by_12.25_.E2.80.93_faerie2_penetrate
https://wiki.wesnoth.org/LotI_Unit_Advancements#Oops.2C_Something_Went_Wrong_.E2.80.93_backup_amla

**Comment by matsjoyce** [comment]
OK. The penetrates stuff was a bug, and I've fixed that. The Vitra advancement was an LotI bug, so thats been fixed. The Oops advancement is meant to be there and isn't missing anything. Hopefully thats everything. Thanks for the report!

**Comment by arodiss** [comment]
Thanks
